name: Law
main: com.github.mouse0w0.law.Main
version: 2.3.1
api-version: 1.13
author: Mouse0w0
commands:
  law:
    usage: /<command>
    permission: law.admin
permissions:
  law.admin.*:
    default: op
  law.bypass.place-block:
    default: false
  law.bypass.break-block:
    default: false
  law.bypass.left-click-block:
    default: false
  law.bypass.right-click-block:
    default: false
  law.bypass.use-item:
    default: false
  law.bypass.left-click-entity:
    default: false
  law.bypass.right-click-entity:
    default: false